
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Database_Fundamentals = 4F,
    Computer_Architecture = 4F,
    Distributed_Computing_Systems = 4F,
    Cyber_Security = 4F,
    Networking = 4F,
    Software_Development = 3F,
    Programming_Skills = 4F,
    Project_Management = 4F,
    Computer_Forensics_Fundamentals = 4F,
    Technical_Communication = 4F,
    AI_ML = 4F,
    Software_Engineering = 4F,
    Business_Analysis = 4F,
    Communication_skills = 4F,
    Data_Science = 4F,
    Troubleshooting_skills = 6F,
    Graphics_Designing = 4F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Role with predicted Role from sample data...\n\n");


Console.WriteLine($"Database_Fundamentals: {4F}");
Console.WriteLine($"Computer_Architecture: {4F}");
Console.WriteLine($"Distributed_Computing_Systems: {4F}");
Console.WriteLine($"Cyber_Security: {4F}");
Console.WriteLine($"Networking: {4F}");
Console.WriteLine($"Software_Development: {3F}");
Console.WriteLine($"Programming_Skills: {4F}");
Console.WriteLine($"Project_Management: {4F}");
Console.WriteLine($"Computer_Forensics_Fundamentals: {4F}");
Console.WriteLine($"Technical_Communication: {4F}");
Console.WriteLine($"AI_ML: {4F}");
Console.WriteLine($"Software_Engineering: {4F}");
Console.WriteLine($"Business_Analysis: {4F}");
Console.WriteLine($"Communication_skills: {4F}");
Console.WriteLine($"Data_Science: {4F}");
Console.WriteLine($"Troubleshooting_skills: {6F}");
Console.WriteLine($"Graphics_Designing: {4F}");
Console.WriteLine($"Role: {16F}");


Console.WriteLine($"\n\nPredicted Role: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

