
// This file was auto-generated by ML.NET Model Builder. 

using CareerAI;

string[] roles = new string[] { "Database Administrator",
    "Hardware Engineer",
    "Application Support Engineer",
    "Cyber Security Specialist",
    "Networking Engineer",
    "Software Developer",
    "API Specialist",
    "Project Manager",
    "Information Security Specialist",
    "Technical Writer",
    "AI ML Specialist",
    "Software tester",
    "Business Analyst",
    "Customer Service Executive",
    "Data Scientist",
    "Helpdesk Engineer",
    "Graphics Designer"
};

int stopper = 0;

while (stopper != 1)
{
    Console.WriteLine("Legend: Skills" +
    "\n0 - Not Interested" +
    "\n1 - Poor" +
    "\n2 - Beginner" +
    "\n3 - Average" +
    "\n4 - Intermediate" +
    "\n5 - Excellent" +
    "\n6 - Professional \n" +
    "\nEnter your skill level for each of the following skills: \n");

    Console.Write("Input Skill Level for Database_Fundamentals: ");
    int Database_Fundamentals = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Computer_Architecture: ");
    int Computer_Architecture = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Distributed_Computing_Systems: ");
    int Distributed_Computing_Systems = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Cyber_Security: ");
    int Cyber_Security = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Networking: ");
    int Networking = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Software_Development: ");
    int Software_Development = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Programming_Skills: ");
    int Programming_Skills = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Project_Management: ");
    int Project_Management = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Computer_Forensics_Fundamentals: ");
    int Computer_Forensics_Fundamentals = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Technical_Communication: ");
    int Technical_Communication = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for AI_ML: ");
    int AI_ML = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Software_Engineering: ");
    int Software_Engineering = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Business_Analysis: ");
    int Business_Analysis = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Communication_skills: ");
    int Communication_skills = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Data_Science: ");
    int Data_Science = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Troubleshooting_skills: ");
    int Troubleshooting_skills = Convert.ToInt32(Console.ReadLine());

    Console.Write("Input Skill Level for Graphics_Designing: ");
    int Graphics_Designing = Convert.ToInt32(Console.ReadLine());

    // Create single instance of sample data from first line of dataset for model input
    MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
    {
        Database_Fundamentals = Database_Fundamentals,
        Computer_Architecture = Computer_Architecture,
        Distributed_Computing_Systems = Distributed_Computing_Systems,
        Cyber_Security = Cyber_Security,
        Networking = Networking,
        Software_Development = Software_Development,
        Programming_Skills = Programming_Skills,
        Project_Management = Project_Management,
        Computer_Forensics_Fundamentals = Computer_Forensics_Fundamentals,
        Technical_Communication = Technical_Communication,
        AI_ML = AI_ML,
        Software_Engineering = Software_Engineering,
        Business_Analysis = Business_Analysis,
        Communication_skills = Communication_skills,
        Data_Science = Data_Science,
        Troubleshooting_skills = Troubleshooting_skills,
        Graphics_Designing = Graphics_Designing,
    };

    // Make a single prediction on the sample data and print results
    var predictionResult = MLModel1.Predict(sampleData);

    Console.WriteLine("Using model to make single prediction -- Comparing actual Role with predicted Role from sample data...\n\n");

    Console.WriteLine("Your inputs: \n\n");

    Console.WriteLine($"Database_Fundamentals: {Database_Fundamentals}");
    Console.WriteLine($"Computer_Architecture: {Computer_Architecture}");
    Console.WriteLine($"Distributed_Computing_Systems: {Distributed_Computing_Systems}");
    Console.WriteLine($"Cyber_Security: {Cyber_Security}");
    Console.WriteLine($"Networking: {Networking}");
    Console.WriteLine($"Software_Development: {Software_Development}");
    Console.WriteLine($"Programming_Skills: {Programming_Skills}");
    Console.WriteLine($"Project_Management: {Project_Management}");
    Console.WriteLine($"Computer_Forensics_Fundamentals: {Computer_Forensics_Fundamentals}");
    Console.WriteLine($"Technical_Communication: {Technical_Communication}");
    Console.WriteLine($"AI_ML: {AI_ML}");
    Console.WriteLine($"Software_Engineering: {Software_Engineering}");
    Console.WriteLine($"Business_Analysis: {Business_Analysis}");
    Console.WriteLine($"Communication_skills: {Communication_skills}");
    Console.WriteLine($"Data_Science: {Data_Science}");
    Console.WriteLine($"Troubleshooting_skills: {Troubleshooting_skills}");
    Console.WriteLine($"Graphics_Designing: {Graphics_Designing}");


    Console.WriteLine($"\n\nPredicted Role: {Convert.ToInt32(predictionResult.PredictedLabel)} - {roles[Convert.ToInt32(predictionResult.PredictedLabel) - 1]}\n\n");

    Console.WriteLine("\nInput more? \n0 - Yes \n1 - No \n");
    stopper = Convert.ToInt32(Console.ReadLine());
}
